fitur_friends/urls.py
from django.conf.urls import url
from .views import index, add_friends_post

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friends_post/$', add_friends_post, name='add_friends_post'),
    ]

fitur_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
 ]

fitur_statistic/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
 ]

fitur_status/urls.py
from django.conf.urls import url
from .views import index, message_post

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_message', message_post, name='add_message'),
 ]

tugas1ppwc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import fitur_statistic.urls as fitur_statistic
import fitur_status.urls as fitur_status
import fitur_profile.urls as fitur_profile
import fitur_friends.urls as fitur_friends
from fitur_status.views import index as index_fitur_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fitur-status/', include(fitur_status, namespace='fitur-status')),
    url(r'^fitur-profile/', include(fitur_profile, namespace='fitur-profile')),
    url(r'^fitur-friends/', include(fitur_friends, namespace='fitur-friends')),
    url(r'^fitur-statistic/', include(fitur_statistic, namespace='fitur-statistic')),
    url(r'^$', index_fitur_status, name='index')
]

fitur_friends/models.py
from django.db import models

class Teman(models.Model) :
	nama_teman = models.CharField(max_length=50)
	url_teman = models.CharField(max_length=50)
	tanggal_teman = models.DateTimeField(auto_now_add=True)

fitur_profile/models.py
from django.db import models

# Create your models here.

fitur_statistic/models.py
from django.db import models

# Create your models here.

fitur_status/models.py
from django.db import models

class Message(models.Model):
    message = models.TextField(max_length=140)
    created_date = models.DateTimeField(auto_now_add=True)

fitur_friends/forms.py
from django import forms
from .models import Teman

class addFriendForms(forms.Form):
        error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
        attrs = {
        'class': 'form-control'
    }
        name = forms.CharField(label='Name', required=True, max_length=30,widget=forms.TextInput(attrs=attrs))
        url = forms.URLField(label='Url Website',required=True,max_length=40,widget=forms.URLInput(attrs=attrs))

fitur_status/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(label='Apa yang sedang kamu pikirkan?', widget=forms.TextInput(attrs=attrs), required=True, max_length=140)

fitur_friends/views.py
from django.shortcuts import render
from .forms import addFriendForms
from .models import Teman
from django.http import HttpResponseRedirect

# Create your views here.
response = {'author' : "Kelompok C"}
def index(request):
    html = 'add_friends/add_friends.html'
    response['addFriendForms'] = addFriendForms
    teman = Teman.objects.all()
    response['teman'] = teman
    return render(request, html, response)

def add_friends_post(request):
    form = addFriendForms(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        teman = Teman(nama_teman=response['name'], url_teman=response['url'])
        teman.save()
        html ='add_friends/friends_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/fitur-friends/')

fitur_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
response = {'author': "Kelompok C"}
profile_image_url = 'static/image/spiderman.png'
name = 'Spider Man'
birthdate = 'October 22, 1962'
gender = 'Male'
expertise = {'one': 'Web-Shooting Ability', 'two': 'Skilled Photographer', 'three': 'Martial Arts Expert'}
description = 'Experienced as a photographer and superhero in several base of operations in US. Also have a side job as an actor, often plays the role of himself in movies.'
email = 'spiderman@gmail.com'

def index(request):
	html = 'fitur_profile/fitur_profile.html'
	response['profile_image_url'] = profile_image_url
	response['name'] = name
	response['birthdate'] = birthdate
	response['gender'] = gender
	response['expertise'] = expertise
	response['description'] = description
	response['email'] = email
	return render(request, html, response)

fitur_statistic/views.py
from django.shortcuts import render
from fitur_status.models import Message
from fitur_profile.views import name as name11
from fitur_friends.models import Teman

# Create your views here.
response = {'author': "Kelompok C"}
def index(request):
    html = 'fitur_statistic/fitur_statistic.html'
    message = Message.objects.all()
    teman = Teman.objects.all()
    response['name'] = name11
    total_message = message.count()
    total_friends = teman.count()
    response['message'] = message
    response['total_friends'] = total_friends

    if (total_message == 0):
        last_message = ""
        response['message'] = last_message
    else:
        last_message = message[message.count() - 1]
        response['message'] = last_message.message
        response['message_date'] = last_message.created_date


    response['total_message'] = total_message

    return render(request, html, response)

fitur_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message
from fitur_profile.views import name as name11

# Create your views here.
response = {'author': "Kelompok C"}
name = name11
def index(request):
    html = 'fitur_status/fitur_status.html'
    response['name'] = name
    response['message_form'] = Message_Form
    message = Message.objects.all()
    response['message'] = message
    return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        message = Message(message=response['message'])
        message.save()
        html ='fitur_status/form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/fitur-status/')

fitur_friends/templates/add_friends/add_friends.html
{% extends "add_friends/layout/base.html" %}

{% block content %}

<section>
  <div class="container">
    <div class="text-center">
    <div class="long-shadow">MY FRIENDS</div>
    <hr>
    <br>
    <h4><b>Tambahkan teman kamu!</b></h4>
    </div>
      <div class="row">
          <div class="col-sm-offset-2 col-sm-8 text-center">
              <form id="form" method="POST" action="{% url 'fitur-friends:add_friends_post'%}">
              {% csrf_token%}
              {{addFriendForms}}
              <br>
              <button type="submit" style="vertical-align:middle;" id="button" class="button"><span>Add</span></button>
              </form>
          </div>
      </div>
  </div>
</section>

<br>
<br>
<br>

<section>

  <h4><b>Teman yang terdaftar:</b></h4>
  <div class="container">
  <div class="flex">
  {% if teman %}
      {% for x in teman %}

      <div class="flex-item text-center">
          <div class="list-friend">
          <br>
          <div align="center"><img alt="User Pic" src="../../static/image/profilepic.png" width="150" height="150" class="img-circle img-responsive" style="text-align: center"></div>
            <h4 id="title-friend" style="text-align: center; color: black">{{x.nama_teman}}</h4>
            <a href="{{x.url_teman}}" target="_blank">{{x.url_teman}}</a>
            <hr>
            <div id="added-friend" style="color: black">added at {{x.tanggal_teman}}</div>
          </div>
      </div>

      {% endfor %}
  {% endif %}
  </div>
  </div>
</section>

{% endblock %}

fitur_friends/templates/add_friends/friends_result.html
{% extends "add_friends/layout/base.html" %}

{% block content %}

<div class="judul-add-friends">
  <h3><b>{{name}}</b> berhasil terdaftar menjadi teman anda!</h3>
</div>

<hr/>

<h6><a href="{% url 'fitur-friends:index' %}">kembali ke halaman friends</a></h6>

{% endblock %}

fitur_friends/templates/add_friends/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="fitur friends">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_friends.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
    <link rel="icon" type="image/ico" href="{% static 'image/profilepic.png' %}" />

    <title>
        {% block title %} Add Friend By {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "add_friends/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}

        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "add_friends/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

fitur_profile/templates/fitur_profile/fitur_profile.html
{% extends "fitur_profile/layout/base.html" %}

{% block content %}
<h1 class="judul-profile"><b>Profile</b></h1>

<br>
<br>

<div class="cover-image">
	<img width="800" height="400" src="../../static/image/mountains.jpg" alt="coverpic">
</div>
<div class="profile-image">
 	<img width="250" height="250" alt="Profile Pic" src="../../static/image/spiderman.png"/>
</div>

<br>
<br>
<br>

<h2><center><b>{{ name }}</b></h2>

<br>
<br>
<hr>

<h4>&emsp;&emsp;<b>Birthdate</b></h4>
<h5>&emsp;&emsp;{{ birthdate }}</h5>

<br>

<h4>&emsp;&emsp;<b>Gender</b></h4>
<h5>&emsp;&emsp;{{ gender }}</h5>

<br>

<h4>&emsp;&emsp;<b>Expertise</b></h4>
<a href="http://marvel.wikia.com/wiki/Web-Shooters" target="_blank"><div class="rcorners1">{{expertise.one}} </div></a>
<a href="https://www.tor.com/2017/07/31/spider-man-homecoming-peter-parker-photographer-smartphone-millennial/" target="_blank"><div class="rcorners2">{{expertise.two}} </div></a>
<a href="http://spiderman.wikia.com/wiki/Way_of_the_Spider" target="_blank"><div class="rcorners3">{{expertise.three}} </div></a>

<br>
<br>

<h4>&emsp;&emsp;<b>Description</b></h4>
<h5>&emsp;&emsp;{{ description }}</h5>

<br>

<h4>&emsp;&emsp;<b>Email</b></h4>
<h5>&emsp;&emsp;{{ email }}</h5>

<br>

<p>
	{{content}}
</p>


{% endblock %}

fitur_profile/templates/fitur_profile/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="fitur profile">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_profile.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
    <link rel="icon" type="image/ico" href="{% static 'image/profilepic.png' %}" />

    <title>
        {% block title %} Profile By {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "fitur_profile/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}

        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "fitur_profile/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

fitur_profile/templates/fitur_profile/partials/footer.html
<p><center>&copy; {{author}}</p>

fitur_profile/templates/fitur_profile/partials/header.html
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
 <div class="container">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="{% url 'fitur-status:index' %}">cTeam</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
     <ul class="nav navbar-nav navbar-right">
       <!-- LINK MENUJU table, dan link menuju home#form -->
       <li><a href="{% url 'fitur-status:index' %}"> Status </a></li>
       <li><a href="{% url 'fitur-profile:index' %}"> Profile </a> </li>
       <li><a href="{% url 'fitur-friends:index' %}"> Friends </a> </li>
       <li><a href="{% url 'fitur-statistic:index' %}"> Statistic </a> </li>
     </ul>
   </div><!--/.nav-collapse -->
 </div>
</nav>

fitur_statistic/templates/fitur_statistic/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="fitur statistic">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_statistic.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
    <link rel="icon" type="image/ico" href="{% static 'image/profilepic.png' %}" />

    <title>
        {% block title %} Statistic By {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "fitur_statistic/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}

        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "fitur_statistic/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

fitur_statistic/templates/fitur_statistic/partials/footer.html
<p><center>&copy; {{author}}</p>

fitur_statistic/templates/fitur_statistic/partials/header.html
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
 <div class="container">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="{% url 'fitur-status:index' %}">cTeam</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
     <ul class="nav navbar-nav navbar-right">
       <!-- LINK MENUJU table, dan link menuju home#form -->
       <li><a href="{% url 'fitur-status:index' %}"> Status </a></li>
       <li><a href="{% url 'fitur-profile:index' %}"> Profile </a> </li>
       <li><a href="{% url 'fitur-friends:index' %}"> Friends </a> </li>
       <li><a href="{% url 'fitur-statistic:index' %}"> Statistic </a> </li>
     </ul>
   </div><!--/.nav-collapse -->
 </div>
</nav>

fitur_status/templates/fitur_status/fitur_status.html
{% extends "fitur_status/layout/base.html" %}

{% block content %}
<div class="judul-update-status">
  <h1><b>Update Status</b></h1>
</div>

<br>

<section name="form" class="status-form">
    <form id="form" method="POST" action="{% url 'fitur-status:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" style="vertical-align:middle;" id="button" class="button"><span>Submit</span></button>
        <br>
    </form>
</section>

<br>
<br>
<hr>

{% for i in message reversed %}
<div class="status-profile">
  <img src='../../static/image/spiderman.png' alt="Profile Pic"/>
  <h4><b>{{ name }}</b></h4>
</div>
<br>
<h4> {{i.message}} </h4>
<h6> {{i.created_date.date}} {{i.created_date.time}}</h6>
<br>
{% endfor %}

{% endblock %}

fitur_status/templates/fitur_status/form_result.html
{% extends "fitur_status/layout/base.html" %}

{% block content %}

<div class="judul-update-status">
  <h3>Status baru anda yang berisi:</h3>
</div>

<textarea readonly rows="1" class="form-control">&quot;{{message}}&quot;
</textarea>

<h4>berhasil di-update!<h4>

<hr/>

<h6><a href="{% url 'fitur-status:index' %}">kembali ke halaman update status</a></h6>

{% endblock %}

fitur_status/templates/fitur_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="fitur status">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_status.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
    <link rel="icon" type="image/ico" href="{% static 'image/profilepic.png' %}" />

    <title>
        {% block title %} Update Status By {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "fitur_status/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}

        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "fitur_status/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

fitur_status/templates/fitur_status/partials/footer.html
<p><center>&copy; {{author}}</p>

fitur_status/templates/fitur_status/partials/header.html
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
 <div class="container">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="{% url 'fitur-status:index' %}">cTeam</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
     <ul class="nav navbar-nav navbar-right">
       <!-- LINK MENUJU table, dan link menuju home#form -->
       <li><a href="{% url 'fitur-status:index' %}"> Status </a></li>
       <li><a href="{% url 'fitur-profile:index' %}"> Profile </a> </li>
       <li><a href="{% url 'fitur-friends:index' %}"> Friends </a> </li>
       <li><a href="{% url 'fitur-statistic:index' %}"> Statistic </a> </li>
     </ul>
   </div><!--/.nav-collapse -->
 </div>
</nav>